QT += quick

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Additional import path used to resolve QML modules just for Qt Quick Designer
QML_DESIGNER_IMPORT_PATH =

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += qml.qrc

SOURCES += \
        DartsController/Controller/dartscontroller.cpp \
        LocalDartsController/localdartscontrollers.cpp \
        LocalDartsController/DartsAssemblers/assembledpc.cpp \
        LocalDartsController/DartsAssemblers/assembledsc.cpp \
        LocalDartsController/Finishes/dartscreatefinishes.cpp \
        LocalDartsController/Finishes/dcfinishbuilder.cpp \
        LocalDartsController/Finishes/defaultthresholds.cpp \
        LocalDartsController/Index/dcindexconverter.cpp \
        LocalDartsController/Index/dpcindexcontroller.cpp \
        LocalDartsController/Index/dscindexcontroller.cpp \
        LocalDartsController/Init/dcinitialize.cpp \
        LocalDartsController/Injectors/dcinjectfinclient.cpp \
        LocalDartsController/Injectors/dcinjectmetaclient.cpp \
        LocalDartsController/Injectors/dpcindexservices.cpp \
        LocalDartsController/Injectors/dpcinjectiptservices.cpp \
        LocalDartsController/Injectors/dpcinjectplaservices.cpp \
        LocalDartsController/Injectors/dscindexinjector.cpp \
        LocalDartsController/Injectors/dscinjectplaservives.cpp \
        LocalDartsController/Injectors/dscinputinjector.cpp \
        LocalDartsController/Injectors/injectdpcroutines.cpp \
        LocalDartsController/Injectors/injectdscroutines.cpp \
        LocalDartsController/Inputs/dcinputbuilder.cpp \
        LocalDartsController/Inputs/dcinputconverter.cpp \
        LocalDartsController/Inputs/dcjsontoinputmodels.cpp \
        LocalDartsController/Inputs/dpcinputadder.cpp \
        LocalDartsController/Inputs/dpcinputevaluator.cpp \
        LocalDartsController/Inputs/dscinputadder.cpp \
        LocalDartsController/Inputs/dscinputevaluator.cpp \
        LocalDartsController/Meta/dcmetabuilder.cpp \
        LocalDartsController/Meta/dcmetaconverter.cpp \
        LocalDartsController/Players/dcconvertplayers.cpp \
        LocalDartsController/Players/dcplayerbuilder.cpp \
        LocalDartsController/Players/dcplayertojson.cpp \
        LocalDartsController/Players/dpcplayerscontext.cpp \
        LocalDartsController/Players/dscplayerscontext.cpp \
        LocalDartsController/Routines/dcaddinput.cpp \
        LocalDartsController/Routines/dccreatewinnerreport.cpp \
        LocalDartsController/Routines/dcgetscoresasjson.cpp \
        LocalDartsController/Routines/dcgetturnvaluesasjson.cpp \
        LocalDartsController/Routines/dcredoturn.cpp \
        LocalDartsController/Routines/dcresetservices.cpp \
        LocalDartsController/Routines/dcundoturn.cpp \
        DartsModelsContext/ByteArrayServices/converttobytearray.cpp \
        DartsModelsContext/dartscontext.cpp \
        LocalDartsModelsContext/DbServices/loadfromstorage.cpp \
        LocalDartsModelsContext/DbServices/savetostorage.cpp \
        LocalDartsModelsContext/IndexesServices/dartsindexbuilder.cpp \
        LocalDartsModelsContext/Injectors/dartsindexinjector.cpp \
        LocalDartsModelsContext/Injectors/dartsinputinjector.cpp \
        LocalDartsModelsContext/Injectors/dartsplayerinjector.cpp \
        LocalDartsModelsContext/Injectors/dartstournamentinjector.cpp \
        LocalDartsModelsContext/Injectors/injectdartsroutines.cpp \
        LocalDartsModelsContext/InputServices/countdartsinputs.cpp \
        LocalDartsModelsContext/InputServices/dartsinputbuilder.cpp \
        LocalDartsModelsContext/InputServices/dartsinputconverter.cpp \
        LocalDartsModelsContext/InputServices/dartsinputdb.cpp \
        LocalDartsModelsContext/InputServices/dartsinputstobytearray.cpp \
        LocalDartsModelsContext/InputServices/getdartsinputs.cpp \
        LocalDartsModelsContext/InputServices/removedartsinputs.cpp \
        LocalDartsModelsContext/InputServices/sortdartsinputs.cpp \
        LocalDartsModelsContext/InputServices/sortdartsinputsbyindexes.cpp \
        LocalDartsModelsContext/PlayerServices/dartsconvertplayer.cpp \
        LocalDartsModelsContext/Routines/addtournamenttodb.cpp \
        LocalDartsModelsContext/Routines/dartsaddinputtodb.cpp \
        LocalDartsModelsContext/Routines/dartsdisplayplayerinput.cpp \
        LocalDartsModelsContext/Routines/dartshideplayerinput.cpp \
        LocalDartsModelsContext/Routines/dartsinputtojson.cpp \
        LocalDartsModelsContext/Routines/dartsresettournament.cpp \
        LocalDartsModelsContext/Routines/dartstournamentrepair.cpp \
        LocalDartsModelsContext/Routines/gettournamentasjson.cpp \
        LocalDartsModelsContext/Routines/gettournamentsasjson.cpp \
        LocalDartsModelsContext/Routines/removetournamentsfromdb.cpp \
        LocalDartsModelsContext/TournamentServices/dartsbuilder.cpp \
        LocalDartsModelsContext/TournamentServices/dartsjsonconverter.cpp \
        LocalDartsModelsContext/TournamentServices/dartsmetamodelbuilder.cpp \
        LocalDartsModelsContext/TournamentServices/dartssetwinner.cpp \
        LocalDartsModelsContext/TournamentServices/dartsverifyconsistency.cpp \
        LocalDartsModelsContext/TournamentServices/dartwinnermodelbuilder.cpp \
        LocalDartsModelsContext/TournamentServices/getdartstournamentfromdb.cpp \
        LocalDartsModelsContext/TournamentServices/getdartstournamentids.cpp \
        LocalDartsModelsContext/TournamentsDbServices/dartsdbcontext.cpp \
        DartsStatistics/dartsstatistics.cpp \
        DartsStatisticsFactory/Injectors/createsnapshotsprovider.cpp \
        DartsStatisticsFactory/Injectors/createstatisticprovider.cpp \
        DartsStatisticsFactory/Injectors/createstatsservices.cpp \
        DartsStatisticsFactory/Injectors/injectstatsroutines.cpp \
        DartsStatisticsFactory/Inputs/createinput.cpp \
        DartsStatisticsFactory/Inputs/inputsdb.cpp \
        DartsStatisticsFactory/Players/createstatmodel.cpp \
        DartsStatisticsFactory/Players/statsmemory.cpp \
        DartsStatisticsFactory/Routines/createstatsreport.cpp \
        DartsStatisticsFactory/Routines/removeinputfromcontext.cpp \
        DartsStatisticsFactory/Routines/resetstatscontext.cpp \
        DartsStatisticsFactory/Routines/updatecurrentstats.cpp \
        DartsStatisticsFactory/Statistics/calculatemiddlevalue.cpp \
        DartsStatisticsFactory/Statistics/updatescorerange.cpp \
        DartsStatisticsFactory/createdartsstatistics.cpp \
        DartsTableContext/dartstabledatacontext.cpp \
        DartsTableContext/dartstablemodel.cpp \
        DartsTableContext/dartstableslas.cpp \
        LocalDartsModelsContext/localdartsmodelscontext.cpp \
        PlayerModelsContext/playerscontext.cpp \
        PlayersContextFactory/DataServices/plajsonbuilder.cpp \
        PlayersContextFactory/DbServices/loadplayermodels.cpp \
        PlayersContextFactory/DbServices/playersdbcontext.cpp \
        PlayersContextFactory/DbServices/saveplayermodels.cpp \
        PlayersContextFactory/ModelsServices/duplicatechecker.cpp \
        PlayersContextFactory/Services/getplayersfromdb.cpp \
        PlayersContextFactory/Services/plabuilder.cpp \
        PlayersContextFactory/createplayerscontext.cpp \
        QmlContext/qmlpropertiesbuilder.cpp \
        Shared/filejsonio.cpp \
        main.cpp

HEADERS += \
    DartsController/Controller/dartscontroller.h \
    DartsController/Controller/idartsctrl.h \
    DartsController/Converters/idcjsontomodel.h \
    DartsController/Converters/idcjsontomodels.h \
    DartsController/Converters/idcmodeltojson.h \
    DartsController/Finishes/dartsconstructslas.h \
    DartsController/Finishes/dcfinishesservices.h \
    DartsController/Finishes/idartsattemptsservice.h \
    DartsController/Finishes/idartsboundaries.h \
    DartsController/Finishes/idartscreatefinishes.h \
    DartsController/Finishes/idartsdivisorvalues.h \
    DartsController/Finishes/idartsfieldvalues.h \
    DartsController/Finishes/idartsfinishesdb.h \
    DartsController/Finishes/idartsmodidentifiers.h \
    DartsController/Finishes/idartsterminaldivisor.h \
    DartsController/Finishes/idartsthresholds.h \
    DartsController/Finishes/idcfinishbuilder.h \
    DartsController/Index/dcindexservices.h \
    DartsController/Index/idcindexcontroller.h \
    DartsController/Inputs/dcinputsservices.h \
    DartsController/Inputs/idcinputadder.h \
    DartsController/Inputs/idcinputbuilder.h \
    DartsController/Inputs/idcinputconverter.h \
    DartsController/Inputs/idcinputevaluator.h \
    DartsController/Meta/dcmetaservices.h \
    DartsController/Meta/idcmetabuilder.h \
    DartsController/Meta/idcmetaconverter.h \
    DartsController/Meta/idcmetamanager.h \
    DartsController/Models/dcindex.h \
    DartsController/Models/dcinput.h \
    DartsController/Models/dcmeta.h \
    DartsController/Models/dcplayer.h \
    DartsController/Players/dcplayersservices.h \
    DartsController/Players/idcplayermanager.h \
    DartsController/Routines/dartscontrollerroutines.h \
    DartsController/Routines/idcaddinput.h \
    DartsController/Routines/idccreatewinnerjson.h \
    DartsController/Routines/idcgetscoresasjson.h \
    DartsController/Routines/idcgetturnvaluesasjson.h \
    DartsController/Routines/idcinitialize.h \
    DartsController/Routines/idcredoturn.h \
    DartsController/Routines/idcresetservices.h \
    DartsController/Routines/idcundoturn.h \
    DartsController/ServicesProvider/dcservices.h \
    LocalDartsController/localdartscontrollers.h \
    LocalDartsController/DartsAssemblers/assembledpc.h \
    LocalDartsController/DartsAssemblers/assembledsc.h \
    LocalDartsController/Finishes/dartsboundaries.h \
    LocalDartsController/Finishes/dartscreatefinishes.h \
    LocalDartsController/Finishes/dartsdefaultattempts.h \
    LocalDartsController/Finishes/dartsdivisors.h \
    LocalDartsController/Finishes/dartsfieldvalues.h \
    LocalDartsController/Finishes/dartsmodidentifiers.h \
    LocalDartsController/Finishes/dartsterminaldivisor.h \
    LocalDartsController/Finishes/dcfinishbuilder.h \
    LocalDartsController/Finishes/dclogisticdb.h \
    LocalDartsController/Finishes/defaultthresholds.h \
    LocalDartsController/Index/dcindexconverter.h \
    LocalDartsController/Index/dpcindexcontroller.h \
    LocalDartsController/Index/dscindexcontroller.h \
    LocalDartsController/Init/dcinitialize.h \
    LocalDartsController/Injectors/dcinjectfinclient.h \
    LocalDartsController/Injectors/dcinjectmetaclient.h \
    LocalDartsController/Injectors/dpcindexservices.h \
    LocalDartsController/Injectors/dpcinjectiptservices.h \
    LocalDartsController/Injectors/dpcinjectplaservices.h \
    LocalDartsController/Injectors/dscindexinjector.h \
    LocalDartsController/Injectors/dscinjectplaservives.h \
    LocalDartsController/Injectors/dscinputinjector.h \
    LocalDartsController/Injectors/injectdpcroutines.h \
    LocalDartsController/Injectors/injectdscroutines.h \
    LocalDartsController/Inputs/dcinputbuilder.h \
    LocalDartsController/Inputs/dcinputconverter.h \
    LocalDartsController/Inputs/dcjsontoinputmodels.h \
    LocalDartsController/Inputs/dpcinputadder.h \
    LocalDartsController/Inputs/dpcinputevaluator.h \
    LocalDartsController/Inputs/dscinputadder.h \
    LocalDartsController/Inputs/dscinputevaluator.h \
    LocalDartsController/Meta/dcmetabuilder.h \
    LocalDartsController/Meta/dcmetaconverter.h \
    LocalDartsController/Meta/dcmetaservice.h \
    LocalDartsController/Meta/dcsettournamentid.h \
    LocalDartsController/Players/dcconvertplayers.h \
    LocalDartsController/Players/dcplayerbuilder.h \
    LocalDartsController/Players/dcplayertojson.h \
    LocalDartsController/Players/dpcplayerscontext.h \
    LocalDartsController/Players/dscplayerscontext.h \
    LocalDartsController/Routines/dcaddinput.h \
    LocalDartsController/Routines/dccreatewinnerreport.h \
    LocalDartsController/Routines/dcgetscoresasjson.h \
    LocalDartsController/Routines/dcgetturnvaluesasjson.h \
    LocalDartsController/Routines/dcredoturn.h \
    LocalDartsController/Routines/dcresetservices.h \
    LocalDartsController/Routines/dcundoturn.h \
    DartsModelsContext/ByteArrayServices/converttobytearray.h \
    DartsModelsContext/DbSLAs/idbcontext.h \
    DartsModelsContext/DbSLAs/imodelconverter.h \
    DartsModelsContext/FileIOSLAs/ifiledataio.h \
    DartsModelsContext/ForeignContextSLAs/DartsPlayerServices.h \
    DartsModelsContext/ForeignContextSLAs/IDartsConvertPlayer.h \
    DartsModelsContext/IndexesDbSLAs/idartsindex.h \
    DartsModelsContext/IndexesSLAs/dartsindexservices.h \
    DartsModelsContext/IndexesSLAs/idartsidxbuilder.h \
    DartsModelsContext/InputModelsSLAs/idartsinput.h \
    DartsModelsContext/InputModelsSLAs/iplayerinput.h \
    DartsModelsContext/InputSLAs/dartsinputservices.h \
    DartsModelsContext/InputSLAs/icountinputmodels.h \
    DartsModelsContext/InputSLAs/isortinputmodels.h \
    DartsModelsContext/InputsDbSLAs/idartsinputbuilder.h \
    DartsModelsContext/InputsDbSLAs/igetinputs.h \
    DartsModelsContext/InputsDbSLAs/iremovedartsinputs.h \
    DartsModelsContext/ModelSLAs/imodel.h \
    DartsModelsContext/Models/DartsPlayer.h \
    DartsModelsContext/Persistence/ipersistence.h \
    DartsModelsContext/PredicateSLAs/imodelpredicate.h \
    DartsModelsContext/Routines/IDartsAddTournament.h \
    DartsModelsContext/Routines/IDartsHideInput.h \
    DartsModelsContext/Routines/IDartsSetWinner.h \
    DartsModelsContext/Routines/idartsaddinputtodb.h \
    DartsModelsContext/Routines/idartsinputstojson.h \
    DartsModelsContext/Routines/idartsinputtojson.h \
    DartsModelsContext/Routines/idartsremovetournaments.h \
    DartsModelsContext/Routines/idartsresettournament.h \
    DartsModelsContext/Routines/idartsrevealinput.h \
    DartsModelsContext/Routines/igettournamentasjson.h \
    DartsModelsContext/Routines/igettournamentsasjson.h \
    DartsModelsContext/Routines/itournamentrepair.h \
    DartsModelsContext/SLAs/abstractdartscontext.h \
    DartsModelsContext/SLAs/dartsmodelsroutines.h \
    DartsModelsContext/SLAs/dartsmodelsservices.h \
    DartsModelsContext/TournamentModels/dartsmetamodel.h \
    DartsModelsContext/TournamentModels/dartstournament.h \
    DartsModelsContext/TournamentModelsSLAs/idartstournament.h \
    DartsModelsContext/TournamentsDbSLAs/idartsbuilder.h \
    DartsModelsContext/TournamentsDbSLAs/igetdartstournament.h \
    DartsModelsContext/TournamentsSLAs/idartsconsistency.h \
    DartsModelsContext/TournamentsSLAs/idartscreatemeta.h \
    DartsModelsContext/TournamentsSLAs/idmcaddindexestotournament.h \
    DartsModelsContext/TournamentsSLAs/igettournamentids.h \
    DartsModelsContext/TournamentsSLAs/iwinnerinfobuilder.h \
    DartsModelsContext/TournamentsSLAs/tournamentservices.h \
    DartsModelsContext/dartscontext.h \
    LocalDartsModelsContext/DbServices/loadfromstorage.h \
    LocalDartsModelsContext/DbServices/savetostorage.h \
    LocalDartsModelsContext/IndexesDbServices/dartsindex.h \
    LocalDartsModelsContext/IndexesServices/dartsindexbuilder.h \
    LocalDartsModelsContext/Injectors/dartsindexinjector.h \
    LocalDartsModelsContext/Injectors/dartsinputinjector.h \
    LocalDartsModelsContext/Injectors/dartsplayerinjector.h \
    LocalDartsModelsContext/Injectors/dartstournamentinjector.h \
    LocalDartsModelsContext/Injectors/injectdartsroutines.h \
    LocalDartsModelsContext/InputServices/countdartsinputs.h \
    LocalDartsModelsContext/InputServices/dartsinput.h \
    LocalDartsModelsContext/InputServices/dartsinputbuilder.h \
    LocalDartsModelsContext/InputServices/dartsinputconverter.h \
    LocalDartsModelsContext/InputServices/dartsinputdb.h \
    LocalDartsModelsContext/InputServices/dartsinputstobytearray.h \
    LocalDartsModelsContext/InputServices/getdartsinputs.h \
    LocalDartsModelsContext/InputServices/removedartsinputs.h \
    LocalDartsModelsContext/InputServices/sortdartsinputs.h \
    LocalDartsModelsContext/InputServices/sortdartsinputsbyindexes.h \
    LocalDartsModelsContext/PlayerServices/dartsconvertplayer.h \
    LocalDartsModelsContext/Routines/addtournamenttodb.h \
    LocalDartsModelsContext/Routines/dartsaddinputtodb.h \
    LocalDartsModelsContext/Routines/dartsdisplayplayerinput.h \
    LocalDartsModelsContext/Routines/dartshideplayerinput.h \
    LocalDartsModelsContext/Routines/dartsinputtojson.h \
    LocalDartsModelsContext/Routines/dartsresettournament.h \
    LocalDartsModelsContext/Routines/dartstournamentrepair.h \
    LocalDartsModelsContext/Routines/gettournamentasjson.h \
    LocalDartsModelsContext/Routines/gettournamentsasjson.h \
    LocalDartsModelsContext/Routines/removetournamentsfromdb.h \
    LocalDartsModelsContext/TournamentServices/dartsbuilder.h \
    LocalDartsModelsContext/TournamentServices/dartsjsonconverter.h \
    LocalDartsModelsContext/TournamentServices/dartsmetamodelbuilder.h \
    LocalDartsModelsContext/TournamentServices/dartssetwinner.h \
    LocalDartsModelsContext/TournamentServices/dartsverifyconsistency.h \
    LocalDartsModelsContext/TournamentServices/dartwinnermodelbuilder.h \
    LocalDartsModelsContext/TournamentServices/getdartstournamentfromdb.h \
    LocalDartsModelsContext/TournamentServices/getdartstournamentids.h \
    LocalDartsModelsContext/TournamentsDbServices/dartsdbcontext.h \
    DartsStatistics/Db/istatsdb.h \
    DartsStatistics/InputRoutines/IRemoveInputFromDb.h \
    DartsStatistics/Inputs/Models/snapshot.h \
    DartsStatistics/Inputs/icreatesnapshot.h \
    DartsStatistics/Inputs/snapshotsservices.h \
    DartsStatistics/Players/ICreateStatModel.h \
    DartsStatistics/Players/Models/currentstats.h \
    DartsStatistics/Players/statisticservices.h \
    DartsStatistics/Report/icreatereport.h \
    DartsStatistics/Routines/IUpdateCurrentStats.h \
    DartsStatistics/Routines/iaddplayerstomem.h \
    DartsStatistics/Routines/iresetmodels.h \
    DartsStatistics/Routines/routineservices.h \
    DartsStatistics/SLAs/idartsstatistics.h \
    DartsStatistics/SLAs/servicescontext.h \
    DartsStatistics/StatsServices/CalcAverage/ICalcAverage.h \
    DartsStatistics/StatsServices/ScoreRange/iupdatescorerange.h \
    DartsStatistics/StatsServices/StatsServices.h \
    DartsStatistics/dartsstatistics.h \
    DartsStatisticsFactory/Injectors/createsnapshotsprovider.h \
    DartsStatisticsFactory/Injectors/createstatisticprovider.h \
    DartsStatisticsFactory/Injectors/createstatsservices.h \
    DartsStatisticsFactory/Injectors/injectstatsroutines.h \
    DartsStatisticsFactory/Inputs/createinput.h \
    DartsStatisticsFactory/Inputs/inputsdb.h \
    DartsStatisticsFactory/Players/createstatmodel.h \
    DartsStatisticsFactory/Players/statsmemory.h \
    DartsStatisticsFactory/Routines/createstatsreport.h \
    DartsStatisticsFactory/Routines/removeinputfromcontext.h \
    DartsStatisticsFactory/Routines/resetstatscontext.h \
    DartsStatisticsFactory/Routines/updatecurrentstats.h \
    DartsStatisticsFactory/Statistics/calculatemiddlevalue.h \
    DartsStatisticsFactory/Statistics/updatescorerange.h \
    DartsStatisticsFactory/createdartsstatistics.h \
    DartsTableContext/DataContextSLAs/idartstabledatacontext.h \
    DartsTableContext/FontMetrics/greatestheight.h \
    DartsTableContext/FontMetrics/greatestwidth.h \
    DartsTableContext/FontMetrics/mhtablesectionmetrics.h \
    DartsTableContext/LinkedList/linkedlist.h \
    DartsTableContext/QMLDartsDataModel/dartsplayerdatamodel.h \
    DartsTableContext/QMLTableMetrics/mhtablecolumnwidth.h \
    DartsTableContext/QMLTableMetrics/mhtablerowheight.h \
    DartsTableContext/TableCellsServices/dartsinitrowvalues.h \
    DartsTableContext/TableSectionsSLAs/itablecellcontext.h \
    DartsTableContext/TableSectionsSLAs/itableinitrowvalues.h \
    DartsTableContext/TableSectionsSLAs/itablesectioncontext.h \
    DartsTableContext/TableSectionsSLAs/itablesectionmanipulator.h \
    DartsTableContext/createqmlvariants.h \
    DartsTableContext/dartsdatacontextitemutility.h \
    DartsTableContext/dartstablecellcontext.h \
    DartsTableContext/dartstablecreatecolumnindices.h \
    DartsTableContext/dartstablecreatecolumns.h \
    DartsTableContext/dartstablecreaterowindices.h \
    DartsTableContext/dartstabledatacontext.h \
    DartsTableContext/dartstabledimensions.h \
    DartsTableContext/dartstablemodel.h \
    DartsTableContext/dartstablesectionmanipulator.h \
    DartsTableContext/dartstablesectionutility.h \
    DartsTableContext/dartstableslas.h \
    DartsTableContext/dptablemodel.h \
    DartsTableContext/dstablemodel.h \
    DartsTableContext/idartstablesectionutility.h \
    DartsTableContext/igetdatafromdatacontext.h \
    DartsTableContext/iqmldatabuilder.h \
    DartsTableContext/itableindicevalues.h \
    LocalDartsModelsContext/localdartsmodelscontext.h \
    PlayerModelsContext/ContextSLA/abstractplayercontext.h \
    PlayerModelsContext/DataSLAs/ijsonbuilder.h \
    PlayerModelsContext/DbSLAs/IPlayersDbContext.h \
    PlayerModelsContext/DbSLAs/PlayersDbSLAs.h \
    PlayerModelsContext/DbSLAs/ifetchdb.h \
    PlayerModelsContext/DbSLAs/igetplayerfromdb.h \
    PlayerModelsContext/DbSLAs/iplayer.h \
    PlayerModelsContext/DbSLAs/iplayerbuilder.h \
    PlayerModelsContext/DbSLAs/isaveplayers.h \
    PlayerModelsContext/IOSLAs/ifiledataio.h \
    PlayerModelsContext/ModelsSLAs/iduplicatechecker.h \
    PlayerModelsContext/playerscontext.h \
    PlayersContextFactory/DataServices/plajsonbuilder.h \
    PlayersContextFactory/DbServices/isaveplayers.h \
    PlayersContextFactory/DbServices/loadplayermodels.h \
    PlayersContextFactory/DbServices/playersdbcontext.h \
    PlayersContextFactory/DbServices/saveplayermodels.h \
    PlayersContextFactory/ModelsServices/duplicatechecker.h \
    PlayersContextFactory/Services/getplayersfromdb.h \
    PlayersContextFactory/Services/plabuilder.h \
    PlayersContextFactory/Services/playermodel.h \
    PlayersContextFactory/createplayerscontext.h \
    QmlContext/qmlpropertiesbuilder.h \
    SetupQmlApp/registerqmldartstabletypes.h \
    SetupQmlApp/registerqmlsingletons.h \
    SetupQmlApp/registerqmltableutils.h \
    SetupQmlApp/registerqmltypes.h \
    SetupQmlApp/setupqmlcontext.h \
    Shared/filejsonio.h

DISTFILES += \
    Ressources/arrow.png \
    Ressources/checkmark.png \
    Ressources/dartpic.jpg \
    Ressources/dartpic.png \
    Ressources/darttournamentmod.png \
    Ressources/fck.png \
    Ressources/fck_jersey_logo.png \
    Ressources/hitler.png \
    Ressources/pngfuel.com.png \
    Ressources/s12_1.jpg \
    Ressources/skull.png \
    Ressources/tuborgclassic.png \
    Ressources/users.png
