#ifndef TESTCONFIGURATION_H
#define TESTCONFIGURATION_H
#define LOCAL_TEST_MODE

#ifdef LOCAL_TEST_MODE
#define TEST_MODE
#endif
#ifdef REMOTE_TEST_MODE
#define TEST_MODE
#endif
#endif // TESTCONFIGURATION_H
